---
title: "Fossil Fuel Supply-Side Policies"
output: html_document
params: 
    selection: input$country
    data: "country_overview_largeDF"
    data_mbl: "moratoria_bans_limitsDF"
    data_sr: "subsidy_removalDF"
    data_div: "divestmentDF"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval=TRUE, message=FALSE, warning=FALSE)
```



## `r params$selection`

<p>&nbsp;</p>


#### Global Climate Risk Index (2017):

    `r params$data['cri']`  

#### Country Greenhouse Gas Emissions (CAIT 2016):

    `r params$data['MTCO2e']` MtCO2e 

#### % Global Emissions:

    `r params$data['global_emissions_percent']` %

<p>&nbsp;</p>

## Policies  
<p>&nbsp;</p>

#### Total number of supply-side policies: 
    
    `r sum(params$data['Policy_total'])`
    
#### Moratoria, Bans, Limitations:  

    `r sum(params$data['Moratoria_bans_limits_total'])`
    
#### Subsidy Removals: 

    `r sum(params$data['Subsidy_removal_total'])`
    
#### Number of Divestments: 

    `r sum(params$data['Divestment_total'])`
    
<p>&nbsp;</p>


## Breakdown of policies across sectors and levels 

<p>&nbsp;</p>

### Government Policies

#### Total number of Governmental Policies: 

    `r sum(params$data['Government_policies_total'])`
    
#### National level governmental policies (Subsidy Removal):

    `r sum(params$data['Subsidy_removal'])`
        
#### National level governmental policies (Moratoria, bans, & limits): 

    `r sum(params$data['mbl_country'])`
        
#### State/city governmental level policies (Moratoria, bans, & limits):

    `r sum(params$data['mbl_city_region'])`
        
#### State/city governmental level policies (Divestments):

    `r sum(params$data['divestment_city_region'])`
    
<p>&nbsp;</p>

### Non-Governmental Policies  

#### Total number of non-governmental policies: 

    `r sum(params$data['Non_Government_policies_total'])`

<p>&nbsp;</p>
<p>&nbsp;</p>